version: "3.8"

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=scheduler
      - MYSQL_USER=default
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
volumes:
  db: